import { ContentItem, BlogPost, Product, Discussion, ChatMessage } from '../types';

// Mock Content Items (Music, Books, Art)
export const mockContentItems: ContentItem[] = [
  {
    id: '1',
    title: 'Neon Dreams',
    description: 'An exploration of cyberpunk soundscapes and digital emotions',
    content_type: 'music',
    image_url: '/images/artwork/abstract-1.png',
    featured: true,
    tags: ['electronic', 'ambient', 'featured'],
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Digital Dreams',
    description: 'A collection of short stories set in near-future urban landscapes',
    content_type: 'book',
    image_url: '/images/artwork/cityscape-1.png',
    featured: false,
    tags: ['fiction', 'cyberpunk', 'anthology'],
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Crystal Visions',
    description: 'Abstract digital art exploring geometric forms and vibrant gradients',
    content_type: 'art',
    image_url: '/images/artwork/abstract-2.png',
    featured: true,
    tags: ['digital art', 'abstract', 'featured'],
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Cosmic Gateway',
    description: 'Surreal landscape art with otherworldly atmospheres',
    content_type: 'art',
    image_url: '/images/artwork/landscape-1.png',
    featured: false,
    tags: ['surreal', 'landscape', 'fantasy'],
    created_at: new Date().toISOString(),
  },
];

// Mock Blog Posts
export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Creative Process Behind My Latest Work',
    slug: 'creative-process-latest-work',
    excerpt: 'Exploring the journey from initial concept to final masterpiece...',
    content: 'Full blog post content here...',
    cover_image: '/images/artwork/abstract-1.png',
    author_name: 'Creator',
    tags: ['process', 'inspiration', 'behind-the-scenes'],
    published: true,
    featured: true,
    view_count: 1234,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Finding Inspiration in Everyday Moments',
    slug: 'finding-inspiration-everyday',
    excerpt: 'How mundane experiences fuel extraordinary creativity...',
    content: 'Full blog post content here...',
    author_name: 'Creator',
    tags: ['inspiration', 'creativity', 'lifestyle'],
    published: true,
    featured: false,
    view_count: 892,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'New Album Release: Behind the Sound',
    slug: 'new-album-release-behind-sound',
    excerpt: 'An in-depth look at the production process of my latest album...',
    content: 'Full blog post content here...',
    author_name: 'Creator',
    tags: ['music', 'production', 'album'],
    published: true,
    featured: false,
    view_count: 567,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Crystal Dreams T-Shirt',
    description: 'Premium black tee with exclusive geometric design',
    price: 32.00,
    image_url: '/images/products/tshirt-1.png',
    category: 'apparel',
    stock_quantity: 50,
    featured: true,
    tags: ['tshirt', 'limited-edition'],
  },
  {
    id: '2',
    name: 'Abstract Flow Print',
    description: 'Limited edition framed art print, signed and numbered',
    price: 45.00,
    image_url: '/images/products/print-1.png',
    category: 'prints',
    stock_quantity: 25,
    featured: true,
    tags: ['print', 'limited-edition', 'signed'],
  },
  {
    id: '3',
    name: 'Neo-Futura Vinyl Album',
    description: 'Complete album collection on premium vinyl',
    price: 35.00,
    image_url: '/images/products/album-1.png',
    category: 'music',
    stock_quantity: 100,
    featured: false,
    tags: ['vinyl', 'music', 'album'],
  },
];

// Mock Discussions
export const mockDiscussions: Discussion[] = [
  {
    id: '1',
    title: 'Favorite Track from the New Album?',
    content: 'Which track resonated with you the most and why?',
    author_name: 'Sarah M.',
    category: 'Music Discussion',
    tags: ['music', 'album', 'discussion'],
    upvotes: 42,
    reply_count: 18,
    pinned: true,
    locked: false,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Book Club Discussion: Chapter 3 Analysis',
    content: 'Let\'s dive deep into the symbolism in chapter 3...',
    author_name: 'Mike D.',
    category: 'Books',
    tags: ['books', 'discussion', 'analysis'],
    upvotes: 28,
    reply_count: 12,
    pinned: false,
    locked: false,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Art Technique Questions',
    content: 'What tools do you use for digital art creation?',
    author_name: 'Alex K.',
    category: 'Art',
    tags: ['art', 'techniques', 'digital'],
    upvotes: 35,
    reply_count: 9,
    pinned: false,
    locked: false,
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
];

// Mock Chat Messages
export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    author_name: 'Sarah',
    message: 'Just listened to the new track - absolutely amazing! 🎵',
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    author_name: 'Mike',
    message: 'Anyone else excited for the book club discussion tonight?',
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    author_name: 'Alex',
    message: 'The art prints just arrived - they look even better in person! 🎨',
    created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    author_name: 'Jordan',
    message: 'Welcome everyone! Feel free to share your thoughts on the latest content',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];
